apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ksmysql.fullname" . }}
  labels:
    {{- include "ksmysql.labels" . | nindent 4 }}
stringData:
  rootUser: {{ .Values.mysql.username }}
  rootHost: '%'
  rootPassword: {{ .Values.mysql.password }}
