apiVersion: v1
kind: Service
metadata:
  name: {{ include "knowstreaming-manager.fullname" . }}
  #name: knowstreaming-manager-km
  labels:
    {{- include "knowstreaming-manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "knowstreaming-manager.selectorLabels" . | nindent 6 }}
