apiVersion: v2
name: knowstreaming-web
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

maintainers:
- email: didicloud@didiglobal.com
  name: didicloud

appVersion: "1.0.0"
